sudo: required
services:
  - docker

before_install:
  - docker build -t frontend_test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run frontend_test npm run test -- --coverage

after_success:
  - docker build -t jculvey/fib-frontend ./frontend
  - docker build -t jculvey/fib-api ./api
  - docker build -t jculvey/fib-worker ./worker
  - docker build -t jculvey/fib-nginx ./nginx
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jculvey/fib-frontend
  - docker push jculvey/fib-api
  - docker push jculvey/fib-worker
  - docker push jculvey/fib-nginx
